\subsection{AMMI}
\label{ammi}

\subsubsection{Theory of the model}

The Additive Main effects and Multiplicative Interaction (AMMI) model is based on two analyses \citep{gauch_statistical_2006} : 
\begin{enumerate}

\item an ANOVA with the following model :

\begin{equation}
Y_{ijk} = \mu + \alpha_{i} + \theta_{j} +  rep_{k}(\theta_{j}) + \eta_{i}\nu_{j} + \varepsilon_{ijk}; \quad \varepsilon_{ijk} \sim \mathcal{N} (0,\sigma^2)
\label{ammi_anova}
\end{equation}

With,
$Y_{ijk}$ the phenotypic value for replication $k$, germplasm $i$ and environment $j$,
$\mu$ the general mean,
$\alpha_{i}$ the effect of germplasm $i$,
$\theta_{j}$ the effect of environment $j$,
$rep_{k}(\theta_{j})$ effect of replication $k$ nested in environment,
$\eta_{i}\nu_{j}$ the effect of interaction germplasm $\times$ environment,
$\varepsilon_{ijk}$ the residuals.\\

\item a PCA which analyse deeper the $G \times E$ interaction: 

\begin{displaymath}
\eta_{i}\nu_{j} = \sum_{n}^{N} \lambda_{n} \gamma_{in} \omega_{jn}
\end{displaymath}

which can also be written:

\begin{displaymath}
\eta_{i}\nu_{j} = \sum_{n}^{N} (\sqrt{\lambda_{n}} \gamma_{in}) (\sqrt{\lambda_{n}} \omega_{jn})
\end{displaymath}

with,
$\eta_{i}\nu_{j}$ interaction of germplasm $i$ with environment $j$,
$N$ the number of dimension (PCA componant) which has as maximum value the number of environment,
$\lambda_{n}$ the eigen value for componant $n$,
$\gamma_{in}$ eigen vector for germplasm $i$ for componant $n$,
$\omega_{jn}$ eigen vector for  environment $j$  for componant $n$.

The data are double centered on environment and germplasm.
The PCA study the structure of the interaction matrix.
The environment are the variable and the germplasm are the individuals.

This PCA allows to detect
\begin{itemize}
\item germplasm that are stable (i.e. contribute less to interaction)
\item which germplasm interact the most with which environment
\item which environment have the same profile regarding interaction
\end{itemize}

\end{enumerate}


The AMMI model can be written:

\begin{equation}
Y_{ijk} = \mu + \alpha_{i} + \theta_{j} + rep_{k}(\theta_{j}) + \sum_{n}^{N} \lambda_{n} \gamma_{in} \omega_{jn} + \varepsilon_{ijk}; \quad \varepsilon_{ijk} \sim \mathcal{N} (0,\sigma^2)
\label{modele_ammi}
\end{equation}

with,

$Y_{ijk}$ the phenotypic value for replication $k$, germplasm $i$ and environment $j$,
$\mu$ the general mean,
$\alpha_{i}$ the effect of germplasm $i$,
$\theta_{j}$ the effect of environment $j$,
$rep_{k}(\theta_{j})$ effect of replication $k$ nested in environment,
$N$ the number of dimension (PCA componant) which has as maximum value the number of environment,
$\lambda_{n}$ the eigen value for componant $n$,
$\gamma_{in}$ eigen vector for germplasm $i$ for componant $n$,
$\omega_{jn}$ eigen vector for  environment $j$  for componant $n$.
$\varepsilon_{ijk}$ the residuals.\\


\subsubsection{Steps with \pack}


\subsubsection{Run the model}
<<message=TRUE,cache=FALSE>>=
ammi = GxE(PPBdata_GxE, vec_variables, gxe_analysis = "AMMI")
@

Lets' see for one variable
<<message=TRUE,cache=FALSE>>=
res_ammi_y1 = ammi$AMMI$y1
@


\subsubsection{Descriptive graph}
<<message=TRUE,cache=FALSE>>=
res_ammi_y1$descriptive$germplasm
@

<<message=TRUE,cache=FALSE>>=
res_ammi_y1$descriptive$location
@

<<message=TRUE,cache=FALSE>>=
res_ammi_y1$descriptive$interaction
@


\subsubsection{ANOVA}

<<message=TRUE,cache=FALSE>>=
anova = res_ammi_y1$ANOVA
@

\paragraph{table of the model}
<<message=TRUE,cache=FALSE>>=
anova$anova_model
@

\paragraph{residuals}
<<message=TRUE,cache=FALSE>>=
anova$residuals
@

\paragraph{variability repartition}
<<message=TRUE,cache=FALSE>>=
anova$variability_repartition
@

\paragraph{location effects}
<<message=TRUE,cache=FALSE>>=
anova$location_effects$effects
@

<<message=TRUE,cache=FALSE>>=
anova$location_effects$barplot_LSD_significant_group
@

\paragraph{germplasm effects}
<<message=TRUE,cache=FALSE>>=
anova$germplasm_effects$effects
@

<<message=TRUE,cache=FALSE>>=
anova$germplasm_effects$intra_variance
@

<<message=TRUE,cache=FALSE>>=
anova$germplasm_effects$barplot_LSD_significant_group
@

<<message=TRUE,cache=FALSE>>=
anova$germplasm_effects$boxplot_variance_intra
@


\paragraph{Interaction matrix}
<<message=TRUE,cache=FALSE>>=
anova$interaction_matrix
@

\subsubsection{PCA}
<<message=TRUE,cache=FALSE>>=
pca = res_ammi_y1$PCA
@

\paragraph{ecovalence}

Ecovalence from \citet{wricke_uber_1962} give part of interaction variance taken by germplasm and environment.
It is an indicator of stability: a low ecovalence means low interaction, i.e. more stability.

Ecovalance of germplasm $i$ is $W_{i}=\sum_{i}^{n} (\eta_{i}\nu_{j})^{2}$

Ecovalance of environment $j$ is $W_{j}=\sum_{j}^{n} (\eta_{i}\nu_{j})^{2}$.

Ecovalances are represented in fonction of mean effects by germplasm and environment.

<<message=TRUE,cache=FALSE>>=
pca$ecovalence
@

\paragraph{biplot}
The results of the PCA is a list divided into three elements as explained in \citet{ceccarelli_manual_2012}:

\begin{itemize}
\item The percentage of variance explained by each composante of the PCA.
In our case, only the two first composant are represented in a biplot.
Note that the sum of variance caught by the two compostant must be as big as possible to be confident in the conclusion of the observations.


<<message=TRUE,cache=FALSE>>=
pca$biplot$variation_dim
@

\item The which won where graph. 
Perpendicular lines divide the biplot into sectors.
The entry which have the largest value in a sector "win" in the location present in that sector.
The information is summarized in the legend of the plot.



<<message=TRUE,cache=FALSE>>=
pca$biplot$which_won_where
@

\item The mean vs stability graph.

\begin{itemize}
\item mean
A red circle define the average location.
An high score mean a greater mean performance of an entry.
Entries with a score above zero means entries with above-average means.
Entries with a score below zero means entries with below-average means.
Note that the distance from the biplot origin to the average location circle (represented with an arrow), is a measure of the relative importance of the entry main effect versus the entry by location interaction.
The longer the arrow is, the more important is entry effect and the more meaningful the selection based on mean performance. 

<<message=TRUE,cache=FALSE>>=
pca$biplot$mean_vs_stability$mean
@

\item stability
This information is related to the ecovalence graph.
The score is equal to the length of the projection.
A high score represents a low stability (i.e. an high entry by location interaction).


<<message=TRUE,cache=FALSE>>=
pca$biplot$mean_vs_stability$stability
@

\end{itemize}


\item The discrimitiveness vs representativeness graph. 
A red circle define the average location, being the virtual better location to test the entries.

The closer a given location is next to the circle, the more desirable it is judged on both discrimination and representativeness.

\begin{itemize}

\item discrimitiveness
The higher the value, the highest the discrimitiveness for environments.

<<message=TRUE,cache=FALSE>>=
pca$biplot$discrimitiveness_vs_representativeness$discrimitiveness
@


\item representativeness
The highest the value, the less representative the environment.

<<message=TRUE,cache=FALSE>>=
pca$biplot$discrimitiveness_vs_representativeness$representativeness
@
\end{itemize}


A CONTINUER 

Representativeness is a key factor to decide how a test location should be used in
genotype evaluation, assuming adequate discriminating ability (Yan et al 2007). The
representativeness should be measured over a number of years in order to assess its
repeatability. A test location must be repeatable across years in ranking genotypes
for it to be considered as highly representative and based on repeatability analysis; a
highly representative test location, which is also highly repeatable by definition, is
ideal for use as core test locations (Yan et al 2011). In a PPB program such as the
one described in Fig. 11, these should be the attributes of the location where to
plant the Stage 1 trials because genotypic differences observed at locations like
these are both repeatable across years and representative of the other farmers fields
in the area. It is crucial for a PPB breeding program to have test locations of this
type.



\subsection{GGE}
\label{gge}

\subsubsection{Theory of the model}

The GGE model is the same than the AMMI model except that the PCA is done on a matrix centered on the environment: germplasm and interaction effects are merged.

The GGE model can be written as followed:

\begin{equation}
Y_{ijk} = \mu + \theta_{j} + rep_{k}(\theta_{j}) + \sum_{n}^{N} \lambda_{n} \gamma_{in} \omega_{jn} + \varepsilon_{ijk}; \quad \varepsilon_{ijk} \sim \mathcal{N} (0,\sigma^2)
\label{modele_gge}
\end{equation}

with,

$Y_{ijk}$ the phenotypic value for replication $k$, germplasm $i$ and environment $j$,
$\mu$ the general mean,
$\theta_{j}$ the effect of environment $j$,
$rep_{k}(\theta_{j})$ effect of replication $k$ nested in environment,
$N$ the number of dimension (PCA componant) which has as maximum value the number of environment,
$\lambda_{n}$ the eigen value for componant $n$,
$\gamma_{in}$ eigen vector for germplasm $i$ for componant $n$,
$\omega_{jn}$ eigen vector for  environment $j$  for componant $n$.
$\varepsilon_{ijk}$ the residuals.\\

This model allow to detect environment where germplasm (and the interaction) behave better : 'which won where' \citep{gauch_statistical_2008,yan_gge_2007}.

\subsubsection{Steps with \pack}


\subsubsection{Run the model}


\subsubsection{Analysis of model outputs}


\subsubsection{Get main effects results}

\paragraph{Germplasm effects}

\paragraph{Environment effects}

\subsubsection{Get $G \times E$ effects results}

\paragraph{interaction plot}

\paragraph{PCA}






